main: com.wheatlogin.App
name: WheatLogin
author: WorldOfWheat
version: 1.0

commands:
  #customban
  wl:
    description: all commands

permissions:
  wheatlogin.admin:
    description: admin permission
    children:
      wheatlogin.admin.help: true
  wheatlogin.player:

  wheatlogin.admin.help:
  description: get admin help message
  wheatlogin.admin.register:


